/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.FileReader;
import java.io.FileNotFoundException;
import java.io.BufferedReader;
import java.io.IOException;

class AppTest {
    @Test
    void tooLowArgNum() throws FileNotFoundException, IOException
    {
      App.working(new String[]{"5"});
      BufferedReader reader = new BufferedReader(new FileReader("logger.txt"));
      assertEquals(reader.readLine(), "Too low number of command line args!");
    }
    @Test
    void nonNumberArg() throws FileNotFoundException, IOException
    {
      App.working(new String[]{"NotANumber", "2", "3", "JSON"});
      BufferedReader reader = new BufferedReader(new FileReader("logger.txt"));
      assertEquals(reader.readLine(), "java.lang.NumberFormatException: For input string: \"NotANumber\"");
    }
    @Test
    void notCSVOrJSONArgs() throws FileNotFoundException, IOException
    {
      App.working(new String[]{"1", "2", "3", "4"});
      BufferedReader reader = new BufferedReader(new FileReader("logger.txt"));
      assertEquals(reader.readLine(), "Bad file format: not CSV or JSON. You write: 4");
    }
    @Test
    void goodArgs() throws FileNotFoundException, IOException
    {
      App.working(new String[]{"1", "2", "3", "JSON"});
      BufferedReader reader = new BufferedReader(new FileReader("logger.txt"));
    }
}
