package eleventh;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest
{
/*  @Test
  public void virtualThreadPerformanceTest()
  {
    long startTime = System.nanoTime();
    App.runTaskViaVirtualThread();
    System.out.println("Время выполнения: " + (System.nanoTime() - startTime) / 1000000);
  }
  @Test
  public void threadPerformanceTest()
  {
    long startTime = System.nanoTime();
    App.runTaskViaExecutor();
    System.out.println("Время выполнения: " + (System.nanoTime() - startTime) / 1000000);
  }*/
  @Test
  public void virtualThreadPiTest()
  {
    long startTime = System.nanoTime();
    App.calculatePiVirtual();
    System.out.println("Время выполнения: " + (System.nanoTime() - startTime) / 1000000);
  }
  @Test
  public void threadPiTest()
  {
    long startTime = System.nanoTime();
    App.calculatePiExecutor();
    System.out.println("Время выполнения: " + (System.nanoTime() - startTime) / 1000000);
  }

}
