package sixth;

import java.net.http.*;
import java.net.URI;
import com.google.gson.*;
import com.google.gson.GsonBuilder;
import com.google.gson.reflect.TypeToken;

import java.util.List;
import java.io.IOException;
import java.lang.reflect.Type;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App
{
  public static void main(String[] args)
  {
    System.out.println("Chuck Norris:");

    String url = "https://api.chucknorris.io/jokes/random";
    HttpRequest request = HttpRequest.newBuilder().uri(URI.create(url)).GET().build();
    HttpClient client = HttpClient.newHttpClient();
    try
    {
      HttpResponse response = client.send(request, HttpResponse.BodyHandlers.ofString());
      JsonObject obj = new Gson().fromJson(response.body().toString(), JsonObject.class);
      String result = obj.get("value").toString();
      System.out.println(result);
    }
    catch(IOException e)
    {
      System.err.println(e);
    }
    catch(InterruptedException e)
    {
      System.err.println(e);
    }

    System.out.println("Braking Bad:");

    String url2 = "https://api.breakingbadquotes.xyz/v1/quotes/173";
    HttpRequest request2 = HttpRequest.newBuilder().uri(URI.create(url2)).GET().build();
    HttpClient client2 = HttpClient.newHttpClient();
    try
    {
      HttpResponse response2 = client2.send(request2, HttpResponse.BodyHandlers.ofString());
      Type listType = new TypeToken< List< Quotes > >(){}.getType();
      List< Quotes > obj2 = new Gson().fromJson(response2.body().toString(), listType);
      for (int i = 0; i < obj2.size(); ++i)
      {
        String result2 = obj2.get(i).getQuote();
        System.out.println(i + ": " + result2);
      }
    }
    catch(IOException e)
    {
      System.err.println(e);
    }
    catch(InterruptedException e)
    {
      System.err.println(e);
    }
  }
}
